### ISSUE TITLE
[ Feature ] 바텀 네비게이션이랑 스크린 연결하기

### ISSUE THREAD

**Issue by sillonjeu** [sillonjeu/Protector_Front#1]
## 🛠 Issue
<img width="317" alt="image" src="https://github.com/sillonjeu/Protector_Front/assets/59414536/6778433f-fdf6-4f1e-9d9f-9e8f2928c2e4">
<img width="219" alt="image" src="https://github.com/sillonjeu/Protector_Front/assets/59414536/34045c86-d23f-4e33-b1b0-406fa65ff7b8">

## 📝 To-do
- [x] 바텀 네비게이션이랑 스크린 연결하기
- [x] 인사말 적기
- [x] 환자코드 컨테이너 뷰 만들기
- [x] 메인 MVVM, service 구축
- [x] 알람 없을 경우 컨테이너 구축
