### ISSUE TITLE
[ Feature ] 질병 솔루션 확인 MVVM 구현

### ISSUE THREAD

**Issue by sillonjeu** [sillonjeu/Protector_Front#10]
## 🛠 Issue
<img width="823" alt="image" src="https://github.com/sillonjeu/Protector_App/assets/59414536/80361c88-b088-49c7-a796-f52c5cd99904">

## 📝 To-do
- [x] 질병 솔루션 확인 M 구현
- [x] 질병 솔루션 확인 MV 구현
- [x] 질병 솔루션 확인 V 구현
- [x] 진단서, 처방전 각각 pdf 링크 구현
- [x] 다이얼로그 구현
