### ISSUE TITLE
[ Feature ] 알람 있을 때 가로로 넘기는 기능 구축

### ISSUE THREAD

**Issue by sillonjeu** [sillonjeu/Protector_Front#3]
## 🛠 Issue
<img width="225" alt="image" src="https://github.com/sillonjeu/Protector_Front/assets/59414536/93327d4b-0398-4b76-8d8e-3d8ebf3c9c1a">

## 📝 To-do
- [x] 알람 있을 때 가로로 넘기는 기능 구축
- [x] 알람 MVVM 모델 구축
- [x] 알람 더미데이터 넣기
- [x] 알람 없을 때 명시하는 뷰 생성
