### ISSUE TITLE
[ Feature ] 스마트워치 -> 앱으로 데이터 공유되는지 확인

### ISSUE THREAD

**Issue by sillonjeu** [sillonjeu/Protector_Front#4]
## 📝 To-do
- [ ] 스마트워치 -> 앱으로 데이터 공유되는지 확인
- [ ] 스마트워치랑 내 핸드폰 연동 확인
- [ ] 뷰 상에 데이터 값 띄우는 부분 임의로 개발
